# @package _group_
num_workers: 32
epochs: 100
start_epoch: 0
batch_size: 256
print_freq: 10
resume: null
world_size: 1
rank: -1
dist_url: tcp://localhost:10001
dist_backend: nccl
seed: 0
gpu: null
multiprocessing_distributed: True
fix_pred_lr: True
log_dir: ${env:HOME:experiments}/simsiam_imagenet
