# @package _group_
train:
  - RandomCrop:
      size: 32
      padding: 4
  - RandomApply:
      - ColorJitter:
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
          hue: 0.1
      p: 0.8
  - RandomGrayscale:
      p: 0.2
  - RandomHorizontalFlip:
      p: 0.5
  - ToTensor: {}
  - Normalize:
      mean: [0.4914, 0.4822, 0.4465]
      std: [0.2023, 0.1994, 0.2010]
