# @package _group_
train:
  - RandomResizedCrop:
      scale: [0.16, 1]
      ratio: [0.75, 1.33]
      size: 224
  - RandomApply:
      - ColorJitter:
          brightness: 0.4
          contrast: 0.4
          saturation: 0.4
          hue: 0.1
      p: 0.8
  - RandomGrayscale:
      p: 0.2
  - RandomApply:
      - GaussianBlur:
          sigma: [.1, 2.]
      p: 0.5
  - RandomHorizontalFlip:
      p: 0.5
  - ToTensor: {}
  - Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
